### ISSUE TITLE
Linter fails on license for contributed files (different author)

### ISSUE THREAD

**Issue by epruesse** [qiime2/q2lint#20]
**Bug Description**

The linter expects the second line of each file to match

```# Copyright (c) [2???-]2018, QIIME 2 development team.```

However, given that I am not part of that team, the copyright notice in the files I contributed must differ.

**References**

1. Build log: https://travis-ci.org/qiime2/q2-alignment/builds/427037044#L704
2. Offending line: `# Copyright (c) 2018, Elmar Pruesse.`

See https://github.com/epruesse/q2-alignment/blob/c6054f17265d34fdf252b8abbc1a551beea1388d/q2_alignment/_sina.py#L2

**Suggestions for fix**

- The linter could just ignore whatever comes after the year. Considering the permissions under the BSD-3-Clause license, the specified author does not actually matter that much to the legal options the Q2 team has. Technically, this should allow multiple lines as well:

```
# Copyright (c) [2???-]2018, QIIME 2 development team,
                2025-2030, some volunteer author
```
- The copyright notice could instead reference an `AUTHORS` file kept with `qiime2` or each individual `q2-xyz` plugin.

**Comment by thermokarst** [comment]
Hey there @epruesse!

> [q2lint wants me to claim you guys wrote the _sina.py](https://github.com/qiime2/q2-alignment/issues/53#issuecomment-420318892)

I think there might be a misunderstanding! You are part of the team too! Anyone who contributes is part of the "QIIME 2 development team", it is really just an ambiguous umbrella term.

> The linter could just ignore whatever comes after the year.

I think for now we aren't really in a position to change this. @ebolyen & I have been very interested in pursuing some alternative licensing options for these "core" QIIME 2 codebases, possibly including some form of a [contributor license agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement), which would be akin to your suggestion of an `AUTHORS` file.

How would you feel about sticking with our default header for now, and instead marking your contributions in some form of comment? That way your attribution is still indicated in the source. I don't know if we can [accept additional copyright claims on these codebases](https://github.com/qiime2/q2-alignment/pull/54/commits/ed1aef144a2ae9a3cf412ed4f9c9f8c06f4031d0#diff-3a14b836cf0dc9e0c31c922b4a34cfcaR10), so I suspect it'll be simpler to go with attribution instead. Sorry, we all recognize that that is less than ideal, and is precisely the reason we are interested in a CLA arrangement. I suspect @ebolyen will chime in with some words about this, too, so stay tuned. Thanks!

**Comment by epruesse** [comment]
> I think there might be a misunderstanding!

Yes, there was. If `development team` refers to everyone contributing then that's all fine with me. Honestly, I personally don't care all that much, just trying to be "correct" about this.
